language:
  - cpp

sudo: required

compiler:
  - clang
  - gcc

os:
  - linux
#  - osx

env:
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=Debug

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - gcc-5
    - g++-5

install:
  - sudo pip install cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install valgrind; fi

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - mkdir Build
  - cd Build
  - cmake ..
  - make
  - valgrind --leak-check=yes ctest --output-on-failure

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
