language:
  - cpp

sudo: required

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - valgrind

install:
  - sudo pip install cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && install valgrind; fi

script:
  - mkdir Build
  - cd Build
  - cmake ..
  - make
  - valgrind --leak-check=yes ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
